### PR TITLE
Fixed error when using npm installed packages

### PR DESCRIPTION
**Pull request by bramhoven**
HI Juan,

I use your extension all the time but when I was using packages installed using npm it gave me error telling me it could not find the specified file. This pull request has fixed that and now both project structures will work, I did a few small test that were successful.

It could probably use some more efficient code but I did not look into that yet.

### CODE REVIEW

**Comment by juanfranblanco** [comment]
This breaks the Dappsys structure, but I will use as a switch configuration :)

**Comment by bramhoven** [comment]
I thought that worked as well, or at least when I tested it. Switch configuration would be great!

**Comment by juanfranblanco** [comment]
@bramhoven  check the latest push, it just uses configurations

**Comment by bramhoven** [comment]
@juanfranblanco great way to fix this issue.

**Comment by juanfranblanco** [comment]
Many thanks for this 👍 💯

**Comment by bramhoven** [comment]
Thank you as well. First time actually trying to contribute to an open source project and working with visual studio code extensions :+1:

**Pull request closed without merging**
