### PR TITLE
Add Solhint linter against with Solium

### PR DESCRIPTION
**Pull request by idrabenia**
Hi @juanfranblanco,

There is list of changes (Issue #34):

1. Add support of Solhint linter
2. Change linter user settings to `linter` and `linterDefaultRules`
3. Move execution of source code validation by solc to separate thread. This allow significantly improve response time of source code validation.
4. Add support of Solhint configuration files.

If you will have any question - welcome! 
I'll be glad to help!

\- Ilya

### CODE REVIEW

**Comment by juanfranblanco** [comment]
Many thanks, but can you please not change the readme, licencing etc, also can you put the pull request in smaller chunks, so I can review it, i find it very hard to see the changes and review them. I can only see those above :D.

**Comment by juanfranblanco** [comment]
Sorry I just realised that you have revert your original changes, hence all the changes to everything. BTW as usual if you don't get a quick response come to the Nethereum gitter channel.

Ok, a quick glance on this.

1. You have replaced the default linter to Solhint, and rename this to "Linter" on settings.
2. You have introduce a base class as Linter in which both Linter implement the common methods, these have been extracted from the original linter and made generic.
3. You have created an specific service for Solhint as per the other linter.
4 .. Still in progress

**Comment by juanfranblanco** [comment]
4. Now this is a more complex, so you have created a child process to validate compilation, which uses another solc than the one using for real compilation. 
This does not seem right.

**Comment by juanfranblanco** [comment]
Overall awesome thanks !! This is great as it gives users an option to use any linter.
Now the real comments:

1. If you could just add the changes for Solhint, I love the Service, base class, configuration.
2. If you can keep the configuration settings the same in user settings, but also file takes preference it will be much better.

3. All the compilation in another thread etc remove it, it won't work with the different solidity configuration, BUT the thought is good, something to keep in mind.

**Comment by idrabenia** [comment]
Hi @juanfranblanco ,

1. I removed support of separate thread for compilation
2. I provide possibilities to use enabledSolium and soliumRules flags, but specify that it's deprecated. It must be work if specified in user settings.
3. "file takes preference it will be much better." it's work such way.

If not difficult, could you review my updates.

Thanks!

**Comment by juanfranblanco** [comment]
Many thanks, that is awesome. Ill have a look tonight. Ill push first another version before merging.

**Comment by alatushkin** [comment]
Any news?

**Comment by juanfranblanco** [comment]
Apologies, so busy. Ill merge now :) and test

**Comment by juanfranblanco** [comment]
@idrabenia pls give me a knock in nethereum gitter if needed. Too many things going on.

**Pull request merged**
