### PR TITLE
Update README with OpenZeppelin proviso

### LINKED ISSUE #70: openzeppelin-solidity imports are highlighted red (but compile fine)
I use `openzeppelin-solidity` package in my project (installed with `npm install --save openzeppelin-solidity`), and my smart contract file has this line:

`import "openzeppelin-solidity/contracts/token/ERC20/StandardToken.sol";`

VS Code highlights `import` in red with the error `Source "openzeppelin-solidity/contracts/token/ERC20/StandardToken.sol" not found`

Everything compiles and works fine, it's just annoying to see an error. Anything can be done about that?

### PR DESCRIPTION
**Pull request by PaulRBerg**
Fixes #70. I found the process of switching to VS Code with solidity a bit clumsy because of this particular issue; the first results on Google weren't that helpful.

### CODE REVIEW

**Comment by obernardovieira** [comment]
I think it's good information to have, but you also need to say that this only work if you are on the root folder with the *node_modules* on that folder. For example, I have projects with subfolders and the solidity code and node_modules inside and that doesn't work.

A folder structure like the one below, would not work. You have to open the IDE in ethereum folder. At least It happens to me.
* client
    * some files ...
* ethereum
    * contracts
    * migrations
    * node_modules
    * yoda yoda ....
* README.md
* yoda yoda ...

**Comment by juanfranblanco** [comment]
Yes correct, support for a solution wide capability is not supported, although you could do something like "ethereum/node_modules".
Also it will be good to add DappSys too.

**Comment by juanfranblanco** [comment]
Nevertheless Ill merge now, and it can be added more info later on.

**Comment by juanfranblanco** [comment]
@PaulRBerg @obernardovieira check the latest readme and see that covers everything

**Comment by PaulRBerg** [comment]
Awesome, thanks Juan!

**Pull request merged**
