### PR TITLE
readme: remove mythx support

### PR DESCRIPTION
**Pull request by joaosantos15**
And link to new extension

### CODE REVIEW

**Comment by joaosantos15** [comment]
@juanfranblanco I had issues locally installing the extension to run the tests, but I believe I deleted all the references to mythx and didn't break anything :)

**Comment by juanfranblanco** [comment]
Can you  change the text to something like: "Mythx analysis tool, has been moved to its own stand alone extension, please download it here:..". Sounds nicer.

**Comment by juanfranblanco** [comment]
That was rather fast btw...

**Comment by joaosantos15** [comment]
@juanfranblanco Done :)

**Pull request merged**
