### PR TITLE
Improve syntax

### PR DESCRIPTION
**Pull request by JamesLefrere**
I started to do some small improvements in an isolated way, but I ended up adding a bunch of different improvements in this PR:

- Refactor `solidity.json` syntax
- Add support for parameters in functions, modifiers, returns, etc
- Differentiate function parameters and variables
- Support variable properties
- Improve events and function definitions
- Improve field storage, enums and structs
- Improve mappings
- Improve imports and `using`
- Improve primitives and support parameters for them
- Support scientific numbers
- Add valid improvements from `vscode-solidity-auditor` (no reason why they shouldn't be here imo)

These syntax grammars are a lot of work to maintain, I had no idea!

One larger change made here is to remove the `*.solidity` name for every line; this should be redundant as VS Code picks up the `scopeName` of `source.solidity` at the end of the document, so all scopes contain it and themes can easily target that.

There are still some outliers I haven't been able to fix yet:

- Function calls with primitives like `address(0)` followed by variables; the variables are not picked up because the `)` closes the pattern.
- Storage with interfaces or structs like `MyStruct public data`; the type is not highlighted, only the type modifiers
- Variables inside global functions like `require` are not highlighted, but types and primitives are.

That said, I think this offers a good improvement:

| Before | After |
|--------|-------|
| <details><summary>View</summary><p>before</p></details> | <details><summary>View</summary><p>after</p></details> |

Cheers!

### CODE REVIEW

**Comment by juanfranblanco** [comment]
@JamesLefrere That is great, also very big!! I need some time to digest it.

**Comment by juanfranblanco** [comment]
@JamesLefrere Ill merge now, if anything surfaces it can be fixed.

**Comment by JamesLefrere** [comment]
@juanfranblanco Awesome! Happy to pitch in if anything comes up.

**Comment by juanfranblanco** [comment]
Thank you, again !! :) I guess you have noticed it has been released already.

**Pull request merged**
