### PR TITLE
Fixed `let` to `const` throughout

### PR DESCRIPTION
**Pull request by joshstevens19**
Replace instances where `const` is applicable over `let`

### CODE REVIEW

**Comment by joshstevens19** [comment]
If all ok can get this merged in so I can do my last PR 👍

**Comment by juanfranblanco** [comment]
I'll review it properly later on / tomorrow. I'm on my phone. Family and things.

**Comment by joshstevens19** [comment]
No worries Juan 👍

**Comment by juanfranblanco** [comment]
Ok, I have changed the linter rules to auto fix this throughout, so I can test locally and then validate changes with yours. This way avoid having to revise everychange, I did not see you changing the linter..

**Comment by juanfranblanco** [comment]
Ok I have done a full diff of the two branches, the tslint applies the rules if the variables are later on a parameter to another method, which is in a way correct (and easier to apply by auto-linting) also other areas that are treated as const are left as let. I will close this but i will add you to the readme as contributor :) as you initiated this.

**Comment by juanfranblanco** [comment]
image

**Pull request closed without merging**
