### PR TITLE
feat: set up `npm publish` for standalone server executable

### LINKED ISSUE #282: Standalone language server
Hi. Would it be possible to create a standalone package for the language server, and keep it separated from the vscode extension. This would allow the usage of the language server in other editors supporting the lsp protocol, like neovim.

I'd be happy to help if you point me in the right direction.

### PR DESCRIPTION
**Pull request by llllvvuu**
resolves #282

The only thing I didn't do is change the `package.json` `name`, since that would also change the VSCode extension name. But `solidity` is taken on NPM, so you'll need to temporarily change the name each time you run `npm publish` and then change it back. This can be done in a GitHub Action.

Publish to NPM: `npm publish`. I tested with [`verdaccio`](https://github.com/verdaccio/verdaccio#publishing) to make sure the `node_modules` that gets installed is minimal (I also uninstalled unused packages). Technically if one wanted to aggressively optimize, one could turn the project into a monorepo and publish the server under a different `package.json` with less `dependencies` (would also solve the naming problem)

Users:
```
npm install -g @juanfranblanco/vscode-solidity-server
vscode-solidity-server --stdio
```

This PR does two things to make this possible:
- adds "files", "bin", and "prepublishOnly" to `package.json` to use `tsup`
- updates `server.ts` to read the default config from `package.json` so that even if the client doesn't send a config, they'll still get the default behavior. This is because if the non-VSCode client has to keep manually copying the client config from `package.json`, it's hard to keep it up-to-date.

The big-looking diff in `server.ts` is just me moving the `onDidChangeConfiguration` logic into a separate function so that it can be run in both `onInitialize` and `onDidChangeConfiguration`.

### CODE REVIEW

**Comment by juanfranblanco** [comment]
Wow thanks this is great!

**Comment by llllvvuu** [comment]
@juanfranblanco did you want to set up an npm account? or I can publish an independent version

**Comment by PierrickGT** [comment]
@llllvvuu  is there any guide available to set this up in Neovim?

**Comment by llllvvuu** [comment]
> @llllvvuu is there any guide available to set this up in Neovim?

I forked nvim-lspconfig: https://github.com/llllvvuu/nvim-lspconfig/tree/feat/solidity_ls

I will make that a PR if/when the npm release becomes available from @juanfranblanco

**Pull request merged**
