### PR TITLE
Load solium config from .soliumrc.json on root project folder

### LINKED ISSUE #103: Add suport for external solium configuration
Similar to solhint https://github.com/juanfranblanco/vscode-solidity/blob/master/src/linter/solhint.ts#L75-L90 it will be great to load the solium configuration from a file.

### PR DESCRIPTION
**Pull request by obernardovieira**
Fix #103 

Probably still needs some extra work, but already in action.

### CODE REVIEW

**Comment by obernardovieira** [comment]
While doing this I found one thing, I think we can reuse some code between linters. Yes, I know they work in different ways, but we can use the same code to load files and also, we can use the same methods name for each linter, which makes code more consistent. I didn't happened an issue for this, because maybe it does not makes sense. Please give me your opinion.

**Comment by juanfranblanco** [comment]
That is a tricky one, especially as we don't control the direction and things might change. Although if it makes sense sure.

**Comment by juanfranblanco** [comment]
One thing that it could be used, is for the client to notify the server of those file changes. So that will be probably the direction to use. That way it could be reused for any other type of file. 

So the client will have something like:
```javascript
    // Options to control the language client
    let clientOptions: LanguageClientOptions = {
        // Register the server for plain text documents
        documentSelector: [{ scheme: 'file', language: 'plaintext' }],
        synchronize: {
            // Notify the server about file changes to '.clientrc files contained in the workspace
            fileEvents: workspace.createFileSystemWatcher('**/.clientrc')
        }
    };

```

and the server this:
```javascript
connection.onDidChangeWatchedFiles(_change => {
    // Monitored files have change in VSCode
    connection.console.log('We received an file change event');
});
```
From the docs
https://code.visualstudio.com/docs/extensions/example-language-server

**Comment by juanfranblanco** [comment]
Many thanks by the way :) 👍

**Comment by AlexXiong97** [comment]
May I ask what if the `.soliumrc.json` file is not in project's root folder? How can I specify the plugin to read from specific folder and add customized solium rules? Thanks!

**Comment by obernardovieira** [comment]
From my experience, it works even with *.soliumrc.json* in any folder inside the project folder. If you have more than one, what I think that happens is that it tries to load one of the files.
You only have to follow the README to make it work.

If you have doubts, ask on gitter.

**Pull request merged**
