### PR TITLE
Tided up imports for project

### PR DESCRIPTION
**Pull request by joshstevens19**
As discussed 

- Third party imports will be casted as a * as named so it makes sense in the code
- Only import what we need in each module from internal classes/functions 

I have 1 more PR to come but no point me doing it until the 2 PR are merged into master.

### CODE REVIEW

**Comment by juanfranblanco** [comment]
Cool, vscodelang is not necessary is external (sorry)

**Comment by juanfranblanco** [comment]
Nice thanks :)

**Comment by joshstevens19** [comment]
If all ok can get this merged in so I can do my last PR 👍

**Comment by juanfranblanco** [comment]
Can you revert vscodeLang to vscode? Reasoning this is for server operations so it does not make any difference. Mainly is not necessary.

I want to avoid changes for changes without value add, if not the next person will come and say, hey why don't we call this vscodeServer (more correct) and yet again another PR to review and go through, validation of changes etc.

Apologies, not being picky, I am just avoid extra work if not necessary.

**Comment by joshstevens19** [comment]
Ok I only named it like that because if anyone imported just the “vscode” module it would end up being even stranger names. Naming it as per the namespace in my eyes makes sense. I understand what your saying happy to change.  

So just to confirm you want me to change vscodelang to vscode for every reference?

**Comment by joshstevens19** [comment]
In file solErrorsToDiaganosticClient.ts vscode and vscode-languageserver are both used hence why I choice a more relevant name for importing vscode-languageserver. 

What do you suggest here? Changing to what you suggested will cause huge confusion + would not compile in that file. 

Let me know your thoughts. Personally I see naming vscodelang only makes it more explicit when used rather then just naming it vscode.

**Comment by juanfranblanco** [comment]
In that scenario it will be vscodeServer, yes I understand. But also see my point, I want to avoid change for the sake of change (not your fault) I do need to add contribution guidelines.

**Comment by joshstevens19** [comment]
No worries I will change it as per above 👍

**Comment by joshstevens19** [comment]
This has now been changed as per your suggestion 👍

**Comment by juanfranblanco** [comment]
@joshstevens19  this one merging was going to be a nightmare with all the let / const changes so I have just done and quickly do it myself, also i have added other rules etc. See the commit reference.

Thanks again for this, interesting exercise.

Btw I have not touched anything but local references, projectService (which as a service could have been ignored the new "rule"), utils (which the name was clashing and could have been ignored too) and errorToDiagnostics. 

Probably I would have give you a much better feedback, tackle it from this end earlier (weekend / mobile) was not an ideal situation.

Thanks again.

**Comment by juanfranblanco** [comment]
Also check both pull requests, I would love to know what linter settings / code formatter you use, although in some scenarios fix all does not really help. I preferred to do this one manually (ish).

**Pull request closed without merging**
