### PR TITLE
Would like this to go into a mythril branch.

### PR DESCRIPTION
**Pull request by rocky**
Adds Mythril version command and some small unrelated things:

* Add .editorconfig to declare what the standards are (feel free to change if I have this wrong or add more)
* Add template for constant return

### CODE REVIEW

**Comment by juanfranblanco** [comment]
Hi, can we remove the .editorconfig as it will force all files to be changed. So by the time you are finished with this branch it will be rather confusing.

Constant return has been replaced for view return.

I would prefer if .gitignore is not changed either.

**Comment by juanfranblanco** [comment]
The overall "theory" for contributing is to be feature specific, ie.. mythrill in this scenario. If not things will get awefully messy

**Comment by rocky** [comment]
Ok. I have pared down the changes into just adding the a Mythril "version" command. Let's get this into a mythril branch soonish. 

Because there is a great lag in reviews, if there are other changes that you would like to make, just make them. Thanks.

**Comment by juanfranblanco** [comment]
You could work in your branch / fork if that makes it easier, there is no need to create a direct branch in here. But it actually helps now to see what can go in or not, simpler to review.

**Comment by juanfranblanco** [comment]
Also you will need to target the mythril branch :) https://github.com/juanfranblanco/vscode-solidity/tree/Mythril and I will merge now.

**Pull request closed without merging**
