### PR TITLE
fix read ECONNRESET of downloading soljson.js

### PR DESCRIPTION
**Pull request by hellodword**
solve #218

### CODE REVIEW

**Comment by hellodword** [comment]
This works fine for me, the tls config of `raw.githubusercontent.com` maybe strange, so let's use the `solc-bin.ethereum.org` instead :)

**Comment by juanfranblanco** [comment]
@hellodword we crossed paths :), I was doing the same myself but using https://binaries.soliditylang.org/bin/ instead, it is the recommended one now https://github.com/ethereum/solc-bin

**Comment by juanfranblanco** [comment]
I was thinking as well of doing the keckack validation as you suggested as the list.json includes the kecckak hash.

**Comment by hellodword** [comment]
> @hellodword we crossed paths :), I was doing the same myself but using https://binaries.soliditylang.org/bin/ instead, it is the recommended one now https://github.com/ethereum/solc-bin

Great!

**Comment by hellodword** [comment]
> I was thinking as well of doing the keckack validation as you suggested as the list.json includes the kecckak hash.

That's nice!

**Comment by juanfranblanco** [comment]
Now if you cannot connect to the server you are doomed anyway :) https://github.com/ethereum/solc-bin/blob/gh-pages/bin/list.json

**Comment by hellodword** [comment]
`v0.0.107` works fine! Thanks @juanfranblanco

**Comment by juanfranblanco** [comment]
Awesome @hellodword  and Thanks!!!

**Pull request closed without merging**
